version: "3.9"

services:
  # ----------------------------
  # KONG - API Gateway
  # ----------------------------
  kong:
    image: kong:3.6
    container_name: kong
    environment:
      - KONG_DATABASE=off  # Run Kong in DB-less mode
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8000, [::]:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, [::]:8001
    ports:
      - "8000:8000"  # Public API endpoint
      - "8001:8001"  # Admin API
    volumes:
      - ./kong:/kong
    depends_on:
      - nginx
    networks:
      - app-network

  # ----------------------------
  # NGINX - Load Balancer
  # ----------------------------
  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - app-network

  # ----------------------------
  # Node App 1
  # ----------------------------
  app1:
    build: ./app
    container_name: app1
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/usersdb
      - INSTANCE_NAME=app1
    depends_on:
      - mongo
    networks:
      - app-network

  # ----------------------------
  # Node App 2
  # ----------------------------
  app2:
    build: ./app
    container_name: app2
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017/usersdb
      - INSTANCE_NAME=app2
    depends_on:
      - mongo
    networks:
      - app-network

  # ----------------------------
  # MongoDB
  # ----------------------------
  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

# Define shared network and volume
networks:
  app-network:

volumes:
  mongo-data:
